name: Weekly Power Rankings

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * 2"
    - cron: "0 10 * * 0"

jobs:
  run-power-ranks:
    runs-on: ubuntu-latest

    steps:
      - name: check out repo
        uses: actions/checkout@v4

      - name: set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: python -m pip install -U pip matplotlib
      
      - name: run power rankings
        run: |
          python power_ranks.py

      - name: Upload preview artifacts
        uses: actions/upload-artifact@v4
        with:
          name: power-ranks-preview
          path: |
            exports/power_ranks_message.txt
            exports/power_ranks.png
            state.json
      
